# sft_limopro.yaml
### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_offload_config.json
flash_attn: fa2
gradient_checkpointing: true

### dataset
dataset: acereason_limopro_15k
cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 16
template: qwen

### output
output_dir: /home/apoorvachavali/A-TML/LLaMA-Factory/qwen_limopro_output
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true
save_total_limit: 2  

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 16
learning_rate: 5.0e-6
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### optimizer
optim: adamw_torch
weight_decay: 0.01
max_grad_norm: 1.0

### logging
report_to: none
